ALTER TABLE problems    ADD COLUMN IF NOT EXISTS language       VARCHAR(16);
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS status         VARCHAR(16) NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS feedback_json  TEXT;
ALTER TABLE drafts      ADD COLUMN IF NOT EXISTS files_json     TEXT;
